cluster.name: "{{ os_cluster_name }}"

node.name: "{{ inventory_hostname }}"

network.host: "0.0.0.0"

http.port: 9200

# âœ… Important for Beats compatibility
compatibility.override_main_response_version: true

discovery.type: single-node

bootstrap.memory_lock: true
